/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bdcor.util.pdf2img.proto;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ImgData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9042976307319894223L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ImgData\",\"namespace\":\"com.bdcor.util.pdf2img.proto\",\"fields\":[{\"name\":\"imgBytes\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.nio.ByteBuffer> imgBytes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ImgData() {}

  /**
   * All-args constructor.
   * @param imgBytes The new value for imgBytes
   */
  public ImgData(java.util.List<java.nio.ByteBuffer> imgBytes) {
    this.imgBytes = imgBytes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return imgBytes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: imgBytes = (java.util.List<java.nio.ByteBuffer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'imgBytes' field.
   * @return The value of the 'imgBytes' field.
   */
  public java.util.List<java.nio.ByteBuffer> getImgBytes() {
    return imgBytes;
  }

  /**
   * Sets the value of the 'imgBytes' field.
   * @param value the value to set.
   */
  public void setImgBytes(java.util.List<java.nio.ByteBuffer> value) {
    this.imgBytes = value;
  }

  /**
   * Creates a new ImgData RecordBuilder.
   * @return A new ImgData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.ImgData.Builder newBuilder() {
    return new com.bdcor.util.pdf2img.proto.ImgData.Builder();
  }

  /**
   * Creates a new ImgData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ImgData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.ImgData.Builder newBuilder(com.bdcor.util.pdf2img.proto.ImgData.Builder other) {
    return new com.bdcor.util.pdf2img.proto.ImgData.Builder(other);
  }

  /**
   * Creates a new ImgData RecordBuilder by copying an existing ImgData instance.
   * @param other The existing instance to copy.
   * @return A new ImgData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.ImgData.Builder newBuilder(com.bdcor.util.pdf2img.proto.ImgData other) {
    return new com.bdcor.util.pdf2img.proto.ImgData.Builder(other);
  }

  /**
   * RecordBuilder for ImgData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ImgData>
    implements org.apache.avro.data.RecordBuilder<ImgData> {

    private java.util.List<java.nio.ByteBuffer> imgBytes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bdcor.util.pdf2img.proto.ImgData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.imgBytes)) {
        this.imgBytes = data().deepCopy(fields()[0].schema(), other.imgBytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ImgData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bdcor.util.pdf2img.proto.ImgData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.imgBytes)) {
        this.imgBytes = data().deepCopy(fields()[0].schema(), other.imgBytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'imgBytes' field.
      * @return The value.
      */
    public java.util.List<java.nio.ByteBuffer> getImgBytes() {
      return imgBytes;
    }

    /**
      * Sets the value of the 'imgBytes' field.
      * @param value The value of 'imgBytes'.
      * @return This builder.
      */
    public com.bdcor.util.pdf2img.proto.ImgData.Builder setImgBytes(java.util.List<java.nio.ByteBuffer> value) {
      validate(fields()[0], value);
      this.imgBytes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'imgBytes' field has been set.
      * @return True if the 'imgBytes' field has been set, false otherwise.
      */
    public boolean hasImgBytes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'imgBytes' field.
      * @return This builder.
      */
    public com.bdcor.util.pdf2img.proto.ImgData.Builder clearImgBytes() {
      imgBytes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ImgData build() {
      try {
        ImgData record = new ImgData();
        record.imgBytes = fieldSetFlags()[0] ? this.imgBytes : (java.util.List<java.nio.ByteBuffer>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
