/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bdcor.util.pdf2img.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Pdf2Img {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Pdf2Img\",\"namespace\":\"com.bdcor.util.pdf2img.proto\",\"types\":[{\"type\":\"record\",\"name\":\"PdfData\",\"fields\":[{\"name\":\"pdfBytes\",\"type\":\"bytes\"}]},{\"type\":\"record\",\"name\":\"ImgData\",\"fields\":[{\"name\":\"imgBytes\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}}]}],\"messages\":{\"convert\":{\"request\":[{\"name\":\"pdfData\",\"type\":\"PdfData\"}],\"response\":\"ImgData\"}}}");
  /**
   */
  com.bdcor.util.pdf2img.proto.ImgData convert(com.bdcor.util.pdf2img.proto.PdfData pdfData) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Pdf2Img {
    public static final org.apache.avro.Protocol PROTOCOL = com.bdcor.util.pdf2img.proto.Pdf2Img.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void convert(com.bdcor.util.pdf2img.proto.PdfData pdfData, org.apache.avro.ipc.Callback<com.bdcor.util.pdf2img.proto.ImgData> callback) throws java.io.IOException;
  }
}