/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bdcor.util.pdf2img.proto;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PdfData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 976669762894220118L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PdfData\",\"namespace\":\"com.bdcor.util.pdf2img.proto\",\"fields\":[{\"name\":\"pdfBytes\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.nio.ByteBuffer pdfBytes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PdfData() {}

  /**
   * All-args constructor.
   * @param pdfBytes The new value for pdfBytes
   */
  public PdfData(java.nio.ByteBuffer pdfBytes) {
    this.pdfBytes = pdfBytes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pdfBytes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pdfBytes = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'pdfBytes' field.
   * @return The value of the 'pdfBytes' field.
   */
  public java.nio.ByteBuffer getPdfBytes() {
    return pdfBytes;
  }

  /**
   * Sets the value of the 'pdfBytes' field.
   * @param value the value to set.
   */
  public void setPdfBytes(java.nio.ByteBuffer value) {
    this.pdfBytes = value;
  }

  /**
   * Creates a new PdfData RecordBuilder.
   * @return A new PdfData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.PdfData.Builder newBuilder() {
    return new com.bdcor.util.pdf2img.proto.PdfData.Builder();
  }

  /**
   * Creates a new PdfData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PdfData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.PdfData.Builder newBuilder(com.bdcor.util.pdf2img.proto.PdfData.Builder other) {
    return new com.bdcor.util.pdf2img.proto.PdfData.Builder(other);
  }

  /**
   * Creates a new PdfData RecordBuilder by copying an existing PdfData instance.
   * @param other The existing instance to copy.
   * @return A new PdfData RecordBuilder
   */
  public static com.bdcor.util.pdf2img.proto.PdfData.Builder newBuilder(com.bdcor.util.pdf2img.proto.PdfData other) {
    return new com.bdcor.util.pdf2img.proto.PdfData.Builder(other);
  }

  /**
   * RecordBuilder for PdfData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PdfData>
    implements org.apache.avro.data.RecordBuilder<PdfData> {

    private java.nio.ByteBuffer pdfBytes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bdcor.util.pdf2img.proto.PdfData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pdfBytes)) {
        this.pdfBytes = data().deepCopy(fields()[0].schema(), other.pdfBytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PdfData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bdcor.util.pdf2img.proto.PdfData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.pdfBytes)) {
        this.pdfBytes = data().deepCopy(fields()[0].schema(), other.pdfBytes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'pdfBytes' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getPdfBytes() {
      return pdfBytes;
    }

    /**
      * Sets the value of the 'pdfBytes' field.
      * @param value The value of 'pdfBytes'.
      * @return This builder.
      */
    public com.bdcor.util.pdf2img.proto.PdfData.Builder setPdfBytes(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.pdfBytes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pdfBytes' field has been set.
      * @return True if the 'pdfBytes' field has been set, false otherwise.
      */
    public boolean hasPdfBytes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pdfBytes' field.
      * @return This builder.
      */
    public com.bdcor.util.pdf2img.proto.PdfData.Builder clearPdfBytes() {
      pdfBytes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public PdfData build() {
      try {
        PdfData record = new PdfData();
        record.pdfBytes = fieldSetFlags()[0] ? this.pdfBytes : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
